### ISSUE TITLE
Not working with pmpro custom fields

### ISSUE THREAD

**Issue by adeguk** [Flutterwave/rave-paidmembership-pro#2]
It has been notice that Rave isnt taking in custom fields created in Pmpro customization using pmpro register helper plugin neither is it saving it; only the default fields are saved. These same fields works well with other payment gateway as expect. It is worth considering...

**Comment by adeguk** [comment]
After several hours of work I found the missing piece "`do_action( 'pmpro_after_checkout', $current_user->ID, $morder );`"; which can either implement it within **pmpro_checkout_before_change_membership_level** or **SendToRave**.

**Comment by Zeus-Bolts** [comment]
Sorry to ask but how do I implement that
